# Generated by Django 2.0.7 on 2020-05-05 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='art_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.TextField(max_length=80)),
                ('desc_of_art', models.TextField(max_length=100000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('about_art', models.TextField(max_length=10000)),
                ('pictures', models.ImageField(upload_to='pictures')),
                ('user', models.ForeignKey(default=567251631792, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=50)),
            ],
        ),
    ]
