# Generated by Django 2.0.7 on 2020-05-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_idea', '0002_auto_20200506_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(default=547422310512, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
