# Generated by Django 2.0.7 on 2020-05-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_idea', '0003_auto_20200507_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='no_idea.art_gallery'),
        ),
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(default=420325687152, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
