# Generated by Django 2.0.7 on 2020-05-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_idea', '0004_auto_20200510_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='art_gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='no_idea.category'),
        ),
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(default=1073696800624, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
