# Generated by Django 2.0.7 on 2020-05-10 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_idea', '0006_auto_20200510_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_gallery',
            name='category',
            field=models.ForeignKey(default=1, on_delete=True, to='no_idea.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(default=217696763696, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
