# Generated by Django 2.0.7 on 2020-05-10 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_idea', '0009_auto_20200510_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_gallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no_idea.category'),
        ),
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(default=802082389872, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
